export const PT_ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TRAINEE_NOT_ASSIGNED: 'TRAINEE_NOT_ASSIGNED',
  PROGRAM_NOT_FOUND: 'PROGRAM_NOT_FOUND',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  ALREADY_ASSIGNED: 'ALREADY_ASSIGNED',
  TRAINEE_ID_REQUIRED: 'TRAINEE_ID_REQUIRED',
  TRAINEE_NOT_FOUND: 'TRAINEE_NOT_FOUND',
  INVITE_ALREADY_PENDING: 'INVITE_ALREADY_PENDING',
} as const;

export const PT_I18N_KEYS = {
  unauthorized: 'pt.errors.unauthorized',
  forbidden: 'pt.errors.forbidden',
  notFound: 'pt.errors.notFound',
  traineeNotAssigned: 'pt.errors.traineeNotAssigned',
  programNotFound: 'pt.errors.programNotFound',
  sessionNotFound: 'pt.errors.sessionNotFound',
  alreadyAssigned: 'pt.errors.alreadyAssigned',
  traineeNotFound: 'pt.errors.traineeNotFound',
  inviteAlreadyPending: 'pt.errors.inviteAlreadyPending',
  traineeIdRequired: 'pt.errors.traineeIdRequired',
  nameRequired: 'pt.errors.nameRequired',
  programTypeInvalid: 'pt.errors.programTypeInvalid',
  sessionTypeInvalid: 'pt.errors.sessionTypeInvalid',
  scheduledDateRequired: 'pt.errors.scheduledDateRequired',
  exerciseNameRequired: 'pt.errors.exerciseNameRequired',
  positiveNumber: 'pt.errors.positiveNumber',
  programCreated: 'pt.messages.programCreated',
  sessionCreated: 'pt.messages.sessionCreated',
  sessionScheduled: 'pt.messages.sessionScheduled',
  exercisesAdded: 'pt.messages.exercisesAdded',
  programUpdated: 'pt.messages.programUpdated',
  programAssigned: 'pt.messages.programAssigned',
  sessionUpdated: 'pt.messages.sessionUpdated',
  inviteSent: 'pt.messages.inviteSent',
  inviteResent: 'pt.messages.inviteResent',
  inviteCancelled: 'pt.messages.inviteCancelled',
  workoutDeleted: 'pt.messages.workoutDeleted',
} as const;
