export const TRAINEE_ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_NOT_ACCESSIBLE: 'SESSION_NOT_ACCESSIBLE',
  OUTSIDE_LOG_WINDOW: 'OUTSIDE_LOG_WINDOW',
  ALREADY_LOGGED: 'ALREADY_LOGGED',
  LOG_LOCKED: 'LOG_LOCKED',
  METRIC_LOCKED: 'METRIC_LOCKED',
  FUTURE_DATE: 'FUTURE_DATE',
} as const;

export const TRAINEE_I18N_KEYS = {
  unauthorized: 'trainee.errors.unauthorized',
  forbidden: 'trainee.errors.forbidden',
  notFound: 'trainee.errors.notFound',
  sessionNotFound: 'trainee.errors.sessionNotFound',
  sessionNotAccessible: 'trainee.errors.sessionNotAccessible',
  outsideLogWindow: 'trainee.errors.outsideLogWindow',
  alreadyLogged: 'trainee.errors.alreadyLogged',
  logLocked: 'trainee.errors.logLocked',
  metricLocked: 'trainee.errors.metricLocked',
  futureDate: 'trainee.errors.futureDate',
  weightRequired: 'trainee.errors.weightRequired',
  positiveNumber: 'trainee.errors.positiveNumber',
  ratingRange: 'trainee.errors.ratingRange',
  painRequired: 'trainee.errors.painRequired',
  templateRequired: 'trainee.errors.templateRequired',
  exerciseRequired: 'trainee.errors.exerciseRequired',
  logSuccess: 'trainee.messages.logSuccess',
  metricSuccess: 'trainee.messages.metricSuccess',
  inviteNotFound: 'trainee.errors.inviteNotFound',
  inviteAccepted: 'trainee.messages.inviteAccepted',
  inviteRejected: 'trainee.messages.inviteRejected',
} as const;
